/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdditionalMenu: typeof import('./src/components/AdditionalMenu/AdditionalMenu.vue')['default']
    AuthorizationForm: typeof import('./src/components/AuthorizationForm/AuthorizationForm.vue')['default']
    BlockScraper: typeof import('./src/components/BlockScraper/BlockScraper.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    RegistrationForm: typeof import('./src/components/RegistrationForm/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/SearchBar.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput/SearchInput.vue')['default']
    VButton: typeof import('./src/components/VButton/VButton.vue')['default']
    VForm: typeof import('./src/components/VForm/VForm.vue')['default']
  }
}
